#!/bin/bash

#the full directory name of the script no matter where it is being called from
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR=`(cd $SCRIPT_DIR/.. && pwd)`

BIN_DIR=$ROOT_DIR/bin
cd $BIN_DIR

if [ ! -d $BIN_DIR/BlackLib ];
then
   git clone --depth=1 https://github.com/yigityuce/BlackLib
else
   cd $BIN_DIR/BlackLib
   git pull
fi

#v1.0
cd $BIN_DIR/BlackLib/v1_0
g++ -O2 -std=c++11 -c BlackLib.cpp -o blacklib.o
ar rcs libblacklib.a blacklib.o
mkdir -p  $ROOT_DIR/libs/blacklib
cp *.h    $ROOT_DIR/libs/blacklib
cp *.a    $ROOT_DIR/libs/blacklib 

#v2.0
#cd $BIN_DIR/BlackLib/v2_0
#for i in $(ls Black*.cpp); do
#  echo $i
#  g++ -O2 -std=c++11 -c $i -o $i.o
#done





