#!/bin/bash

# GPIO Control
# Isaac Maia


#the full directory name of the script no matter where it is being called from
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR=`(cd $SCRIPT_DIR/.. && pwd)`
CSD_DIR=$ROOT_DIR/csd


destroy()
{
  exit 0
}

trap 'destroy' SIGINT
trap 'destroy' SIGSEGV


set_dir() {
    GPIO=$1
    DIR="$2"

    if [ ! -d  /sys/class/gpio/gpio$GPIO  ]
    then
       echo "ERROR: GPIO $GPIO is not active!"
    else
       echo $DIR > /sys/class/gpio/gpio$GPIO/direction      
    fi
}


set_val() {
    GPIO=$1
    VAL="$2"
    if [ ! -d  /sys/class/gpio/gpio$GPIO  ]
    then
       echo "ERROR: GPIO $GPIO is not active!"
    else
       echo $VAL > /sys/class/gpio/gpio$GPIO/value
    fi
}

export_gpio()
{
    GPIO="$1"
    echo $GPIO > /sys/class/gpio/export     
}

unexp_gpio()
{
    GPIO="$1"
    if [ -d  /sys/class/gpio/gpio$GPIO  ]
    then
       set_val $GPIO "0"
       echo $GPIO > /sys/class/gpio/unexport     
    fi
}


toggle_gpio() {
    GPIO="$1"

    if [ ! -d  /sys/class/gpio/gpio$GPIO  ]
    then
       echo "ERROR: GPIO $GPIO is not active!"
    else
       CUR_VAL=`cat /sys/class/gpio/gpio$GPIO/value`
       if [ "$CUR_VAL" == "1" ]
       then
           set_val $GPIO "0"
       else
           set_val $GPIO "1"
       fi
    fi
}


show_help()
{
  echo "usage: rob_ctl [OPTIONS]"
  echo "-e, --export  : export a GPIO port"
  echo "-g, --gpio    : current gpio"
  echo "-d, --dir     : gpio direction : in / out(default)"
  echo "-t, --toggle  : toggles GPIO value"
  echo "-v, --val     : sets GPIO value"
  echo "-u, --unexp   : unexport GPIO"
}

args=$(getopt -o e:g:d:t:v:u:h -l export:,dir:,toggle:,val:,unexp:,help  -- "$@")
eval set -- "$args"

while true ; do
     case "$1" in          
             -e|--export)
                 GPIO=$2
                 export_gpio $2 
                 sleep 1
                 set_dir $GPIO "out"
                 echo "GPIO $GPIO active!"
                 ;;     
             -g|--gpio)
                 GPIO=$2
                 ;;                                    
             -d|--dir)
                 DIR=$2
                 set_dir $GPIO $DIR
                 ;;                                    
             -t|--toggle)
                 GPIO=$2
                 toggle_gpio $GPIO
                 ;;                                                     
             -v|--val)
                 VAL=$2
                 set_val $GPIO $VAL
                 ;;                                    
             -u|--unexp)
                 GPIO=$2
                 unexp_gpio $GPIO
                 ;;                                                       
             -h|--help)
                 show_help                 
                 exit 0
                ;;                                
             --)
                 # No more options left.
                 shift ;
                 break;;
     esac
     shift
done
    
exit 0
